// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TPlab4.Repos;

#nullable disable

namespace TPlab4.Migrations
{
    [DbContext(typeof(TPlab4Context))]
    [Migration("20231117002430_intentocincomil")]
    partial class intentocincomil
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("tpfinal.Models.Asistencia", b =>
                {
                    b.Property<int>("IIDAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDAsistencia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IIDAsistencia"));

                    b.Property<int>("ContAsistencia")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<int>("IDCuerpoActivo")
                        .HasColumnType("int");

                    b.HasKey("IIDAsistencia");

                    b.HasIndex("IDCuerpoActivo");

                    b.ToTable("Asistencia");
                });

            modelBuilder.Entity("tpfinal.Models.CuerpoActivo", b =>
                {
                    b.Property<int>("IDCuerpoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCuerpoActivo");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDCuerpoActivo"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Direccion")
                        .HasColumnType("int");

                    b.Property<int>("Duracion")
                        .HasColumnType("int");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDCuerpoActivo");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("CuerpoActivo");
                });

            modelBuilder.Entity("tpfinal.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDepartamento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Departamento");
                });

            modelBuilder.Entity("tpfinal.Models.Equipamiento", b =>
                {
                    b.Property<int>("IDEquipamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDEquipamiento");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDEquipamiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRevicion")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDEquipamiento");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Equipamiento");
                });

            modelBuilder.Entity("tpfinal.Models.Unidades", b =>
                {
                    b.Property<int>("IDUnidades")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDUnidades");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDUnidades"));

                    b.Property<DateTime>("FechaRevicion")
                        .HasColumnType("smalldatetime");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDUnidades");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("tpfinal.Models.Asistencia", b =>
                {
                    b.HasOne("tpfinal.Models.CuerpoActivo", "CuerpoActivo")
                        .WithMany()
                        .HasForeignKey("IDCuerpoActivo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuerpoActivo");
                });

            modelBuilder.Entity("tpfinal.Models.CuerpoActivo", b =>
                {
                    b.HasOne("tpfinal.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("tpfinal.Models.Equipamiento", b =>
                {
                    b.HasOne("tpfinal.Models.Departamento", "Departamento")
                        .WithMany()
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Departamento");
                });
#pragma warning restore 612, 618
        }
    }
}
